apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-api
  labels:
    app: inference-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inference-api
  template:
    metadata:
      labels:
        app: inference-api
    spec:
      containers:
        - name: inference-api
          image: your-dockerhub-username/inference-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: mlops-secrets  # Use Kubernetes Secrets for .env vars
