apiVersion: batch/v1
kind: Job
metadata:
  name: monitor-job
spec:
  template:
    spec:
      containers:
        - name: monitor
          image: your-dockerhub-username/mlops-monitoring:latest
          command: ["python", "monitoring/log_stats.py"]
          envFrom:
            - secretRef:
                name: mlops-secrets
      restartPolicy: Never
  backoffLimit: 3
