apiVersion: v1
kind: Service
metadata:
  name: inference-service
spec:
  selector:
    app: inference-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP  # Change to LoadBalancer or NodePort if needed
